// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByE0uOqEXKqLyZsAg-uBb1Sqy45l9Oc_g',
    appId: '1:460375326472:web:ccb89c63f9b95d391776bd',
    messagingSenderId: '460375326472',
    projectId: 'todoapplication-801a8',
    authDomain: 'todoapplication-801a8.firebaseapp.com',
    storageBucket: 'todoapplication-801a8.firebasestorage.app',
    measurementId: 'G-FE2TD78NTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeGagfz4MiQ0NPMJPtWp5Tsi5DgGOHK1E',
    appId: '1:460375326472:android:c66060032fc927da1776bd',
    messagingSenderId: '460375326472',
    projectId: 'todoapplication-801a8',
    storageBucket: 'todoapplication-801a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFQaObhYVLQdCIcE1Dwb8al3uT6gudMw',
    appId: '1:460375326472:ios:4ebc0f4e9f9bf1fa1776bd',
    messagingSenderId: '460375326472',
    projectId: 'todoapplication-801a8',
    storageBucket: 'todoapplication-801a8.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsFQaObhYVLQdCIcE1Dwb8al3uT6gudMw',
    appId: '1:460375326472:ios:4ebc0f4e9f9bf1fa1776bd',
    messagingSenderId: '460375326472',
    projectId: 'todoapplication-801a8',
    storageBucket: 'todoapplication-801a8.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByE0uOqEXKqLyZsAg-uBb1Sqy45l9Oc_g',
    appId: '1:460375326472:web:4233a01a11a289791776bd',
    messagingSenderId: '460375326472',
    projectId: 'todoapplication-801a8',
    authDomain: 'todoapplication-801a8.firebaseapp.com',
    storageBucket: 'todoapplication-801a8.firebasestorage.app',
    measurementId: 'G-P6DVZQFDHP',
  );
}
